# Generated by Django 5.2.6 on 2025-10-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0003_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
