# Generated by Django 5.2.8 on 2025-11-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='outfit_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
